name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: tools
        key: ${{ runner.os }}-${{ hashFiles('build.cake') }}
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - uses: actions/checkout@v1
    - uses: ecampidoglio/cake-action@v1.1.1
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      with:
        target: GitHub
